tasks:
  - init: |
      pip install dwave-ocean-sdk==4.5.0
      pip install -r requirements.txt
    command: |
      streamlit run --server.port 8501 bin_packing_app.py

ports:
  - port: 8501
    onOpen: open-browser